#server:
#  port: 8082
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/food_application
#    username: root
#    password: "@Ubonmusic98"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#


server:
  port: 8082
#spring:
#  datasource:
#    url: jdbc:h2:mem:springBootDB
#    username: sa
#    password: 
#    driverClassName: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2